name: Airrohr Firmware Flasher CI

on: [push, pull_request, fork]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: ["3.9"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Install qt5 OS X Packages
        if: runner.os == 'macOS'
        run: brew install qt@5
      - name: Install qt5 Ubuntu Packages
        if: runner.os == 'Linux'
        run: sudo apt-get update -qq && sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev qttools5-dev-tools make
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run build script (Linux)
        if: runner.os == 'Linux'
        run: make deps dist
        shell: bash
      - name: Run build script (OS X)
        if: runner.os == 'macOS'
        run: make deps dmg
        shell: bash
      - name: Archive built binaries
        uses: actions/upload-artifact@v3
        with:
          name: airrohr-flasher-dist-${{ matrix.os }}-python${{ matrix.python-version }}
          path: dist/airrohr-flasher
